name: Release

on:
  push:
    branches:
      - main

jobs:
  call-test-workflow:
    uses: BlueBrain/BlueCelluLab/.github/workflows/test.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-and-publish:
    name: Build, publish on PyPI and make a GitHub release
    runs-on: ubuntu-latest
    needs: call-test-workflow
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Fetch the tag, if any. If not tagged, create a patch tag
        uses: anothrNick/github-tag-action@1.69.0
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch


      - name: Build a source tarball and wheel
        run: |
            pip install build
            python -m build --sdist --wheel .

      - name: Get and store tag from 'Bump version and push tag' step
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=${{ steps.tag.outputs.new_tag }}" >> $GITHUB_ENV
      - name: Get and store tag from triggered tag push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          generate_release_notes: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}